"""Initial migration

Revision ID: 3c60a693c3b1
Revises: 
Create Date: 2025-02-16 15:39:12.970088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c60a693c3b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_tracker',
    sa.Column('tracker_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('current_points_in', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('tracker_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('total_points_earned', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dublbubl',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('points_in', sa.Integer(), nullable=False),
    sa.Column('points_out', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_table('dublbubl_history',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('creator_username', sa.String(length=150), nullable=False),
    sa.Column('points_in', sa.Integer(), nullable=False),
    sa.Column('points_out', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.String(length=255), nullable=False),
    sa.Column('date_archived', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dublbubl_history')
    op.drop_table('dublbubl')
    op.drop_table('users')
    op.drop_table('points_tracker')
    # ### end Alembic commands ###
